/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BannerBanner: typeof import('./components/Banner/Banner.vue')['default']
    CommonPageFooter: typeof import('./components/common/PageFooter.vue')['default']
    CommonPageFooterGlass: typeof import('./components/common/PageFooterGlass.vue')['default']
    CommonPageFooterMetal: typeof import('./components/common/PageFooterMetal.vue')['default']
    DemoBlock: typeof import('./components/DemoBlock.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalStatusError: typeof import('./components/GlobalStatus/Error.vue')['default']
    GlobalStatusLoading: typeof import('./components/GlobalStatus/Loading.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    HomeActivityList: typeof import('./components/home/ActivityList.vue')['default']
    HomeHeaderHome: typeof import('./components/home/HeaderHome.vue')['default']
    HomeQuickEntry: typeof import('./components/home/QuickEntry.vue')['default']
    HomeRideDataCard: typeof import('./components/home/RideDataCard.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    UniEcharts: typeof import('uni-echarts')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['default']
    WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdGap: typeof import('wot-design-uni/components/wd-gap/wd-gap.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNotify: typeof import('wot-design-uni/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdTabbar: typeof import('wot-design-uni/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('wot-design-uni/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
  }
}
